<a href="https://colab.research.google.com/github/Juan1mera/dap-2024/blob/main/les03/rep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [2]:
import numpy as np

arr = np.random.random((10, 10))
min_val = arr.min()
max_val = arr.max()

print("Array:\n", arr)
print("Min:", min_val)
print("Max:", max_val)

Array:
 [[0.62781646 0.58067298 0.09196054 0.68189015 0.07284652 0.98830349
  0.16576887 0.21287549 0.32341005 0.51485157]
 [0.82243768 0.94734329 0.99229658 0.8859902  0.17863167 0.82183456
  0.03185719 0.32352498 0.28748161 0.91005408]
 [0.75128453 0.48432226 0.02463824 0.21479178 0.23739487 0.81061322
  0.05819949 0.87286378 0.14218554 0.55401177]
 [0.78005345 0.54028524 0.19524393 0.60531046 0.69050342 0.83018153
  0.98224394 0.64960681 0.30482145 0.32859154]
 [0.03620099 0.28353683 0.85857801 0.02427022 0.82118962 0.96647299
  0.64287344 0.74067041 0.15620984 0.4345866 ]
 [0.96944298 0.77932684 0.24096666 0.05664853 0.58598215 0.18874953
  0.92568074 0.0610512  0.40059629 0.99986407]
 [0.47635635 0.18351904 0.14768929 0.62245908 0.52830246 0.1718689
  0.94102228 0.78784451 0.94240613 0.22937779]
 [0.65997158 0.18539633 0.21170626 0.43315558 0.25352579 0.09487365
  0.52866141 0.65802653 0.30524036 0.9514088 ]
 [0.02562759 0.99996788 0.29709372 0.09697611 0.11554112 0.25030542
  0.3

2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [19]:
arr = np.zeros((8, 8), dtype=int)
# Establecer elementos alternados en 1 para el patrón de tablero de ajedrez
arr[::2, ::2] = 1  # Establecer 1 en filas pares, columnas pares
arr[1::2, 1::2] = 1  # Establecer 1 en filas impares, columnas impares

print("Матрица шахматной доски:\n", arr)

Матрица шахматной доски:
 [[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [4]:
z = np.arange(11)
z[(z > 3) & (z < 8)] *= -1

print("Измененное расположение:", z)

Измененное расположение: [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


5. Поменяйте 1 и 2 строки матрицы

In [5]:
z = np.arange(25).reshape(5, 5)
z[[0, 1]] = z[[1, 0]]  # Intercambiar filas 0 y 1

print("Матрица после замены строк 1 и 2:\n", z)

Матрица после замены строк 1 и 2:
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [18]:
z = np.random.random((10, 2))
x, y = z[:, 0], z[:, 1]  # Extraer coordenadas x e y
r = np.sqrt(x**2 + y**2)  # Radio: sqrt(x^2 + y^2)
theta = np.arctan2(y, x)  # Ángulo: arctan(y/x)
polar = np.column_stack((r, theta))  # Combinar en un arreglo de 10x2

print("Декартовы координаты:\n", z)
print("Полярные координаты (r, theta):\n", polar)

Декартовы координаты:
 [[0.23822629 0.8681674 ]
 [0.52078175 0.62504579]
 [0.02093438 0.71681165]
 [0.40799045 0.29986927]
 [0.52755815 0.50672524]
 [0.20214774 0.38684045]
 [0.5667273  0.19140618]
 [0.79496958 0.03294337]
 [0.71421064 0.74634051]
 [0.13762692 0.16434211]]
Полярные координаты (r, theta):
 [[0.90025907 1.30298678]
 [0.81356983 0.87614279]
 [0.71711728 1.54159977]
 [0.50633762 0.63382588]
 [0.73149714 0.76525853]
 [0.43647365 1.08926323]
 [0.59817736 0.32571083]
 [0.79565187 0.04141609]
 [1.03301549 0.80739307]
 [0.21435834 0.87363841]]


7. Заменить максимальный элемент массива на ноль

In [7]:
z = np.random.random(10)
z[z.argmax()] = 0

print("Исправление после замены максимального значения на 0:", z)

Исправление после замены максимального значения на 0: [0.11626579 0.         0.83947114 0.48012939 0.52690646 0.12493406
 0.30282715 0.007827   0.01716691 0.56435375]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [16]:
z = np.ones(10)
i = np.random.randint(0, len(z), 20)
unique_indices = np.unique(i)  # Obtener índices únicos
z[unique_indices] += 1  # Sumar 1 a los elementos en los índices únicos

print("Исправление после добавления 1 к уникальным индексам:", z)

Исправление после добавления 1 к уникальным индексам: [2. 2. 2. 2. 2. 2. 2. 2. 2. 1.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [13]:
z = np.array([1, 2, 3, 4, 5])
n = len(z) * 4 - 3  # Nueva longitud: 5*4 - 3 = 17 (5 valores + 3 ceros entre cada uno)
new_arr = np.zeros(n, dtype=z.dtype)
new_arr[::4] = z  # Colocar los valores originales en los índices 0, 4, 8, 12, 16

print("Вектор с тремя нулями между значениями:", new_arr)

Вектор с тремя нулями между значениями: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


10. Найти ближайшее к заданному значению число в заданном массиве

In [20]:
z = np.arange(100)
v = np.random.uniform(0, 100)
closest = z[np.abs(z - v).argmin()]

print("Array:", z)
print("Значение:", v)
print("Ближайшее значение:", closest)

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Значение: 78.22228876424828
Ближайшее значение: 78


### 1. Какой тип (dtype) будут иметь элементы массива?

```
# a) int64
# b) float64
# c) float128
# d) complex128
# e) float64
# f) int64
# g) bool
# h) <U1
# i) <U21
# j) complex128
```

### 2. Что будет выведено в консоль и почему?

```python
# a) '41' (string '4' concatenated with '1')
# b) True (boolean True from [3] or integer -4)
# c) -4 (boolean False from [3] and integer -4)
# d) 1 (True converted to int64)
# e) ValueError (complex number cannot be converted to int64)
# f) '1j' (complex number converted to string)
# g) '333' (string '3' repeated three times)
```

### 3. Каков результат операции?

```python
# a) array([[1., 1., 1., 1., 1.], [1., 1., 1., 1., 1.], [1., 1., 1., 1., 1.]])
# b) array([[3.14, 3.14, 3.14, 3.14, 3.14], [3.14, 3.14, 3.14, 3.14, 3.14], [3.14, 3.14, 3.14, 3.14, 3.14]])
# c) array([0., 0.25, 0.5, 0.75, 1.])
# d) array([[1, 0, 0], [0, 3, 0], [0, 0, 5]])
# e) AttributeError (no such function np.smile)
# f) 3x3 array with random floats in [0, 1)
# g) array([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]])
# h) array of length 3 with uninitialized values
```

### 4. Дан двумерный массив X, что будет выведено в консоль?

```python
# a) 3
# b) 7
# c) array([4])
# d) array([4, 8])
# e) array([[3, 5], [7, 6]])
# f) array([6, 8])
# g) array([7, 6, 8, 8])
# h) array([7, 6, 8, 8])
# i) array([[3, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]])
# j) array([[3, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]])
# k) array([[3, 2], [1, 7]])
# l) array([[3, 2], [1, 7]])
# m) array([[7, 7, 6, 1], [8, 8, 6, 7], [4, 2, 5, 3]])
```

### 5. Дан двумерный массив grid, в чем различее между операциями?

```python
# np.split(grid, [2]): Splits into two sub-arrays along axis 0 (rows): [0:2, :] and [2:, :]
# np.split(grid, [2], axis=1): Splits into two sub-arrays along axis 1 (columns): [:, 0:2] and [:, 2:]
```

### 6. В чем различие между операциями?

```python
# [1, 2, 3] + [3, 2, 1]: List concatenation, results in [1, 2, 3, 3, 2, 1]
# np.array([1, 2, 3]) + np.array([3, 2, 1]): Element-wise addition, results in array([4, 4, 4])
```

### 7. Как в CodeLab измерить время выполнения кода?

```python
%timeit <code>
```

### 8. Дан массив X, каковы результаты операций?

```python
# Assuming M is meant to be X
# a) np.sum(X): 72
# b) np.sum(X, axis=1): array([14, 29, 21])
# c) np.sum(X, axis=0): array([11, 17, 17, 19])
# d) np.sum(X, axis=2): ValueError (axis 2 is out of bounds for 2D array)
# e) np.sum(X, 1): array([14, 29, 21])
# f) sum(X): array([11, 17, 17, 19])
# g) sum(X, 1): TypeError (Python's sum does not support axis argument)
```

### 9. Дан массив X, что будет выведено в консоль?

```python
# a) array([False, False, False, True])
# b) array([True, True, False, False])
# c) array([1, 2])
# d) array([4])
# e) array([1, 2, 4])
```

### 10. В чем преимущество массивов NumPy по сравнению с обычными списками. Чем обусловлено это преимущество?

NumPy arrays are faster and more memory-efficient than Python lists due to their fixed-type, contiguous memory storage and vectorized operations implemented in C, which avoid Python's object overhead and enable efficient computation.